#pragma once
#include <cstdio>
#include <windows.h> // Kế thừa trực tiếp cấu trúc lõi của hệ điều hành
#include "PEFILE_CUSTOM_STRUCTS.h"

class PE32FILE
{
public:
    PE32FILE(char* _NAME, FILE* _Ppefile);
    ~PE32FILE();
    void PrintInfo();

private:
    char* NAME;
    FILE* Ppefile;
    int _import_directory_count, _import_directory_size;
    int _basreloc_directory_count;

    // CẤU TRÚC HEADER 32-BIT CHÍNH THỐNG CỦA WINDOWS SDK
    IMAGE_DOS_HEADER         PEFILE_DOS_HEADER;
    IMAGE_NT_HEADERS32       PEFILE_NT_HEADERS; // Sử dụng NT Headers 32-bit cố định

    // DOS HEADER FIELDS
    DWORD PEFILE_DOS_HEADER_EMAGIC;
    LONG  PEFILE_DOS_HEADER_LFANEW;

    // RICH HEADER INFO
    RICH_HEADER_INFO PEFILE_RICH_HEADER_INFO;
    RICH_HEADER      PEFILE_RICH_HEADER;

    // NT_HEADERS.Signature
    DWORD PEFILE_NT_HEADERS_SIGNATURE;

    // NT_HEADERS.FileHeader
    WORD PEFILE_NT_HEADERS_FILE_HEADER_MACHINE;
    WORD PEFILE_NT_HEADERS_FILE_HEADER_NUMBER0F_SECTIONS;
    WORD PEFILE_NT_HEADERS_FILE_HEADER_SIZEOF_OPTIONAL_HEADER;

    // NT_HEADERS.OptionalHeader (CẤU CẤU TRÚC ĐẶC TRƯNG PE32)
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_MAGIC;
    BYTE      PEFILE_NT_HEADERS_OPTIONAL_HEADER_MAJORLINKERVERSION;
    BYTE      PEFILE_NT_HEADERS_OPTIONAL_HEADER_MINORLINKERVERSION;
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_SIZEOF_CODE;
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_SIZEOF_INITIALIZED_DATA;
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_SIZEOF_UNINITIALIZED_DATA;
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_ADDRESSOF_ENTRYPOINT;
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_BASEOF_CODE;
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_BASEOF_DATA;  // Trường đặc trưng riêng của PE32
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_IMAGEBASE;   // 4 bytes trên kiến trúc 32-bit tĩnh
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_SECTION_ALIGNMENT;
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_FILE_ALIGNMENT;
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_SIZEOF_IMAGE;
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_SIZEOF_HEADERS;

    // DATA DIRECTORIES STRUC
    IMAGE_DATA_DIRECTORY PEFILE_EXPORT_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_IMPORT_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_RESOURCE_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_EXCEPTION_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_SECURITY_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_BASERELOC_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_DEBUG_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_ARCHITECTURE_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_GLOBALPTR_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_TLS_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_LOAD_CONFIG_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_BOUND_IMPORT_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_IAT_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_DELAY_IMPORT_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_COM_DESCRIPTOR_DIRECTORY;

    // MẢNG CON TRỎ ÁNH XẠ CHUẨN WINDOWS SDK CHỐNG LỖI C3646
    PIMAGE_SECTION_HEADER    PEFILE_SECTION_HEADERS;
    PIMAGE_IMPORT_DESCRIPTOR PEFILE_IMPORT_TABLE;
    PIMAGE_BASE_RELOCATION   PEFILE_BASERELOC_TABLE;

    // ADDRESS RESOLVERS FUNCTIONS
    int  locate(DWORD VA);
    DWORD resolve(DWORD VA, int index);

    // PARSERS LOGIC INTERNAL
    void ParseFile();
    void ParseDOSHeader();
    void ParseNTHeaders();
    void ParseSectionHeaders();
    void ParseImportDirectory();
    void ParseBaseReloc();
    void ParseRichHeader();

    // PRINT INFO PRESENTATION FUNCTIONS
    void PrintFileInfo();
    void PrintDOSHeaderInfo();
    void PrintRichHeaderInfo();
    void PrintNTHeadersInfo();
    void PrintSectionHeadersInfo();
    void PrintImportTableInfo();
    void PrintBaseRelocationsInfo();
};