#pragma once
#include <cstdio>
#include <windows.h> // Gọi cấu trúc chuẩn hệ điều hành từ winntdef.h đã sửa
#include "PEFILE_CUSTOM_STRUCTS.h"

class PE64FILE
{
public:
    PE64FILE(char* _NAME, FILE* _Ppefile);
    ~PE64FILE();
    void PrintInfo();

private:
    char* NAME;
    FILE* Ppefile;
    int _import_directory_count, _import_directory_size;
    int _basreloc_directory_count;

    // CẤU TRÚC HEADER TIÊU CHUẨN CỦA WINDOWS SDK
    IMAGE_DOS_HEADER        PEFILE_DOS_HEADER;
    IMAGE_NT_HEADERS64      PEFILE_NT_HEADERS; // Khung NT Header x64 cố định

    // DOS HEADER FIELDS
    DWORD PEFILE_DOS_HEADER_EMAGIC;
    LONG  PEFILE_DOS_HEADER_LFANEW;

    // RICH HEADER INFO
    RICH_HEADER_INFO PEFILE_RICH_HEADER_INFO;
    RICH_HEADER      PEFILE_RICH_HEADER;

    // NT_HEADERS.Signature
    DWORD PEFILE_NT_HEADERS_SIGNATURE;

    // NT_HEADERS.FileHeader
    WORD PEFILE_NT_HEADERS_FILE_HEADER_MACHINE;
    WORD PEFILE_NT_HEADERS_FILE_HEADER_NUMBER0F_SECTIONS;
    WORD PEFILE_NT_HEADERS_FILE_HEADER_SIZEOF_OPTIONAL_HEADER;

    // NT_HEADERS.OptionalHeader
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_MAGIC;
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_SIZEOF_CODE;
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_SIZEOF_INITIALIZED_DATA;
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_SIZEOF_UNINITIALIZED_DATA;
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_ADDRESSOF_ENTRYPOINT;
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_BASEOF_CODE;
    ULONGLONG PEFILE_NT_HEADERS_OPTIONAL_HEADER_IMAGEBASE; // 8 bytes chuẩn trên cấu trúc x64
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_SECTION_ALIGNMENT;
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_FILE_ALIGNMENT;
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_SIZEOF_IMAGE;
    DWORD     PEFILE_NT_HEADERS_OPTIONAL_HEADER_SIZEOF_HEADERS;

    // DATA DIRECTORIES STRUC
    IMAGE_DATA_DIRECTORY PEFILE_EXPORT_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_IMPORT_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_RESOURCE_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_EXCEPTION_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_SECURITY_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_BASERELOC_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_DEBUG_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_ARCHITECTURE_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_GLOBALPTR_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_TLS_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_LOAD_CONFIG_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_BOUND_IMPORT_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_IAT_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_DELAY_IMPORT_DIRECTORY;
    IMAGE_DATA_DIRECTORY PEFILE_COM_DESCRIPTOR_DIRECTORY;

    // MẢNG CON TRỎ ÁNH XẠ KHÍT THEO WINDOWS SDK
    PIMAGE_SECTION_HEADER    PEFILE_SECTION_HEADERS; // Sửa lỗi C3646 biến mất hoàn toàn
    PIMAGE_IMPORT_DESCRIPTOR PEFILE_IMPORT_TABLE;
    PIMAGE_BASE_RELOCATION   PEFILE_BASERELOC_TABLE;

    // ADDRESS RESOLVERS FUNCTIONS
    int  locate(DWORD VA);
    DWORD resolve(DWORD VA, int index);

    // PARSERS LOGIC INTERNAL
    void ParseFile();
    void ParseDOSHeader();
    void ParseNTHeaders();
    void ParseSectionHeaders();
    void ParseImportDirectory();
    void ParseBaseReloc();
    void ParseRichHeader();

    // PRINT INFO PRESENTATION FUNCTIONS
    void PrintFileInfo();
    void PrintDOSHeaderInfo();
    void PrintRichHeaderInfo();
    void PrintNTHeadersInfo();
    void PrintSectionHeadersInfo();
    void PrintImportTableInfo();
    void PrintBaseRelocationsInfo();
};